/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thxsoft.vds.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MessageEvaluationType implements org.apache.thrift.TEnum {
  Like(1),
  Dislike(2),
  CancelLike(3),
  CancelDislike(4);

  private final int value;

  private MessageEvaluationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MessageEvaluationType findByValue(int value) { 
    switch (value) {
      case 1:
        return Like;
      case 2:
        return Dislike;
      case 3:
        return CancelLike;
      case 4:
        return CancelDislike;
      default:
        return null;
    }
  }
}
