/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thxsoft.vds.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ReqLoadComments implements org.apache.thrift.TBase<ReqLoadComments, ReqLoadComments._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReqLoadComments");

  private static final org.apache.thrift.protocol.TField SENDER_CONTEXT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("senderContextID", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SENDER_MESSAGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("senderMessageID", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReqLoadCommentsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReqLoadCommentsTupleSchemeFactory());
  }

  public long senderContextID; // required
  public long senderMessageID; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SENDER_CONTEXT_ID((short)1, "senderContextID"),
    SENDER_MESSAGE_ID((short)2, "senderMessageID");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SENDER_CONTEXT_ID
          return SENDER_CONTEXT_ID;
        case 2: // SENDER_MESSAGE_ID
          return SENDER_MESSAGE_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SENDERCONTEXTID_ISSET_ID = 0;
  private static final int __SENDERMESSAGEID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SENDER_CONTEXT_ID, new org.apache.thrift.meta_data.FieldMetaData("senderContextID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "ContextID")));
    tmpMap.put(_Fields.SENDER_MESSAGE_ID, new org.apache.thrift.meta_data.FieldMetaData("senderMessageID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "MessageID")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReqLoadComments.class, metaDataMap);
  }

  public ReqLoadComments() {
  }

  public ReqLoadComments(
    long senderContextID,
    long senderMessageID)
  {
    this();
    this.senderContextID = senderContextID;
    setSenderContextIDIsSet(true);
    this.senderMessageID = senderMessageID;
    setSenderMessageIDIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReqLoadComments(ReqLoadComments other) {
    __isset_bitfield = other.__isset_bitfield;
    this.senderContextID = other.senderContextID;
    this.senderMessageID = other.senderMessageID;
  }

  public ReqLoadComments deepCopy() {
    return new ReqLoadComments(this);
  }

  @Override
  public void clear() {
    setSenderContextIDIsSet(false);
    this.senderContextID = 0;
    setSenderMessageIDIsSet(false);
    this.senderMessageID = 0;
  }

  public long getSenderContextID() {
    return this.senderContextID;
  }

  public ReqLoadComments setSenderContextID(long senderContextID) {
    this.senderContextID = senderContextID;
    setSenderContextIDIsSet(true);
    return this;
  }

  public void unsetSenderContextID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SENDERCONTEXTID_ISSET_ID);
  }

  /** Returns true if field senderContextID is set (has been assigned a value) and false otherwise */
  public boolean isSetSenderContextID() {
    return EncodingUtils.testBit(__isset_bitfield, __SENDERCONTEXTID_ISSET_ID);
  }

  public void setSenderContextIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SENDERCONTEXTID_ISSET_ID, value);
  }

  public long getSenderMessageID() {
    return this.senderMessageID;
  }

  public ReqLoadComments setSenderMessageID(long senderMessageID) {
    this.senderMessageID = senderMessageID;
    setSenderMessageIDIsSet(true);
    return this;
  }

  public void unsetSenderMessageID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SENDERMESSAGEID_ISSET_ID);
  }

  /** Returns true if field senderMessageID is set (has been assigned a value) and false otherwise */
  public boolean isSetSenderMessageID() {
    return EncodingUtils.testBit(__isset_bitfield, __SENDERMESSAGEID_ISSET_ID);
  }

  public void setSenderMessageIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SENDERMESSAGEID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SENDER_CONTEXT_ID:
      if (value == null) {
        unsetSenderContextID();
      } else {
        setSenderContextID((Long)value);
      }
      break;

    case SENDER_MESSAGE_ID:
      if (value == null) {
        unsetSenderMessageID();
      } else {
        setSenderMessageID((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SENDER_CONTEXT_ID:
      return Long.valueOf(getSenderContextID());

    case SENDER_MESSAGE_ID:
      return Long.valueOf(getSenderMessageID());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SENDER_CONTEXT_ID:
      return isSetSenderContextID();
    case SENDER_MESSAGE_ID:
      return isSetSenderMessageID();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReqLoadComments)
      return this.equals((ReqLoadComments)that);
    return false;
  }

  public boolean equals(ReqLoadComments that) {
    if (that == null)
      return false;

    boolean this_present_senderContextID = true;
    boolean that_present_senderContextID = true;
    if (this_present_senderContextID || that_present_senderContextID) {
      if (!(this_present_senderContextID && that_present_senderContextID))
        return false;
      if (this.senderContextID != that.senderContextID)
        return false;
    }

    boolean this_present_senderMessageID = true;
    boolean that_present_senderMessageID = true;
    if (this_present_senderMessageID || that_present_senderMessageID) {
      if (!(this_present_senderMessageID && that_present_senderMessageID))
        return false;
      if (this.senderMessageID != that.senderMessageID)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ReqLoadComments other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ReqLoadComments typedOther = (ReqLoadComments)other;

    lastComparison = Boolean.valueOf(isSetSenderContextID()).compareTo(typedOther.isSetSenderContextID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSenderContextID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.senderContextID, typedOther.senderContextID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSenderMessageID()).compareTo(typedOther.isSetSenderMessageID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSenderMessageID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.senderMessageID, typedOther.senderMessageID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ReqLoadComments(");
    boolean first = true;

    sb.append("senderContextID:");
    sb.append(this.senderContextID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("senderMessageID:");
    sb.append(this.senderMessageID);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReqLoadCommentsStandardSchemeFactory implements SchemeFactory {
    public ReqLoadCommentsStandardScheme getScheme() {
      return new ReqLoadCommentsStandardScheme();
    }
  }

  private static class ReqLoadCommentsStandardScheme extends StandardScheme<ReqLoadComments> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReqLoadComments struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SENDER_CONTEXT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.senderContextID = iprot.readI64();
              struct.setSenderContextIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SENDER_MESSAGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.senderMessageID = iprot.readI64();
              struct.setSenderMessageIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReqLoadComments struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SENDER_CONTEXT_ID_FIELD_DESC);
      oprot.writeI64(struct.senderContextID);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SENDER_MESSAGE_ID_FIELD_DESC);
      oprot.writeI64(struct.senderMessageID);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReqLoadCommentsTupleSchemeFactory implements SchemeFactory {
    public ReqLoadCommentsTupleScheme getScheme() {
      return new ReqLoadCommentsTupleScheme();
    }
  }

  private static class ReqLoadCommentsTupleScheme extends TupleScheme<ReqLoadComments> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ReqLoadComments struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSenderContextID()) {
        optionals.set(0);
      }
      if (struct.isSetSenderMessageID()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSenderContextID()) {
        oprot.writeI64(struct.senderContextID);
      }
      if (struct.isSetSenderMessageID()) {
        oprot.writeI64(struct.senderMessageID);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ReqLoadComments struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.senderContextID = iprot.readI64();
        struct.setSenderContextIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.senderMessageID = iprot.readI64();
        struct.setSenderMessageIDIsSet(true);
      }
    }
  }

}

