/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thxsoft.vds.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ResCreateUserProfile implements org.apache.thrift.TBase<ResCreateUserProfile, ResCreateUserProfile._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ResCreateUserProfile");

  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CREATED_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("createdUserId", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ResCreateUserProfileStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ResCreateUserProfileTupleSchemeFactory());
  }

  public ErrorDesc error; // required
  public String createdUserId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ERROR((short)1, "error"),
    CREATED_USER_ID((short)2, "createdUserId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ERROR
          return ERROR;
        case 2: // CREATED_USER_ID
          return CREATED_USER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ErrorDesc.class)));
    tmpMap.put(_Fields.CREATED_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("createdUserId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "UID")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ResCreateUserProfile.class, metaDataMap);
  }

  public ResCreateUserProfile() {
  }

  public ResCreateUserProfile(
    ErrorDesc error,
    String createdUserId)
  {
    this();
    this.error = error;
    this.createdUserId = createdUserId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ResCreateUserProfile(ResCreateUserProfile other) {
    if (other.isSetError()) {
      this.error = new ErrorDesc(other.error);
    }
    if (other.isSetCreatedUserId()) {
      this.createdUserId = other.createdUserId;
    }
  }

  public ResCreateUserProfile deepCopy() {
    return new ResCreateUserProfile(this);
  }

  @Override
  public void clear() {
    this.error = null;
    this.createdUserId = null;
  }

  public ErrorDesc getError() {
    return this.error;
  }

  public ResCreateUserProfile setError(ErrorDesc error) {
    this.error = error;
    return this;
  }

  public void unsetError() {
    this.error = null;
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return this.error != null;
  }

  public void setErrorIsSet(boolean value) {
    if (!value) {
      this.error = null;
    }
  }

  public String getCreatedUserId() {
    return this.createdUserId;
  }

  public ResCreateUserProfile setCreatedUserId(String createdUserId) {
    this.createdUserId = createdUserId;
    return this;
  }

  public void unsetCreatedUserId() {
    this.createdUserId = null;
  }

  /** Returns true if field createdUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetCreatedUserId() {
    return this.createdUserId != null;
  }

  public void setCreatedUserIdIsSet(boolean value) {
    if (!value) {
      this.createdUserId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((ErrorDesc)value);
      }
      break;

    case CREATED_USER_ID:
      if (value == null) {
        unsetCreatedUserId();
      } else {
        setCreatedUserId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ERROR:
      return getError();

    case CREATED_USER_ID:
      return getCreatedUserId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ERROR:
      return isSetError();
    case CREATED_USER_ID:
      return isSetCreatedUserId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ResCreateUserProfile)
      return this.equals((ResCreateUserProfile)that);
    return false;
  }

  public boolean equals(ResCreateUserProfile that) {
    if (that == null)
      return false;

    boolean this_present_error = true && this.isSetError();
    boolean that_present_error = true && that.isSetError();
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (!this.error.equals(that.error))
        return false;
    }

    boolean this_present_createdUserId = true && this.isSetCreatedUserId();
    boolean that_present_createdUserId = true && that.isSetCreatedUserId();
    if (this_present_createdUserId || that_present_createdUserId) {
      if (!(this_present_createdUserId && that_present_createdUserId))
        return false;
      if (!this.createdUserId.equals(that.createdUserId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ResCreateUserProfile other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ResCreateUserProfile typedOther = (ResCreateUserProfile)other;

    lastComparison = Boolean.valueOf(isSetError()).compareTo(typedOther.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, typedOther.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreatedUserId()).compareTo(typedOther.isSetCreatedUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreatedUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createdUserId, typedOther.createdUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ResCreateUserProfile(");
    boolean first = true;

    sb.append("error:");
    if (this.error == null) {
      sb.append("null");
    } else {
      sb.append(this.error);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("createdUserId:");
    if (this.createdUserId == null) {
      sb.append("null");
    } else {
      sb.append(this.createdUserId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (error != null) {
      error.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResCreateUserProfileStandardSchemeFactory implements SchemeFactory {
    public ResCreateUserProfileStandardScheme getScheme() {
      return new ResCreateUserProfileStandardScheme();
    }
  }

  private static class ResCreateUserProfileStandardScheme extends StandardScheme<ResCreateUserProfile> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ResCreateUserProfile struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.error = new ErrorDesc();
              struct.error.read(iprot);
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CREATED_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.createdUserId = iprot.readString();
              struct.setCreatedUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ResCreateUserProfile struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.error != null) {
        oprot.writeFieldBegin(ERROR_FIELD_DESC);
        struct.error.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.createdUserId != null) {
        oprot.writeFieldBegin(CREATED_USER_ID_FIELD_DESC);
        oprot.writeString(struct.createdUserId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResCreateUserProfileTupleSchemeFactory implements SchemeFactory {
    public ResCreateUserProfileTupleScheme getScheme() {
      return new ResCreateUserProfileTupleScheme();
    }
  }

  private static class ResCreateUserProfileTupleScheme extends TupleScheme<ResCreateUserProfile> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ResCreateUserProfile struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetError()) {
        optionals.set(0);
      }
      if (struct.isSetCreatedUserId()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetError()) {
        struct.error.write(oprot);
      }
      if (struct.isSetCreatedUserId()) {
        oprot.writeString(struct.createdUserId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ResCreateUserProfile struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.error = new ErrorDesc();
        struct.error.read(iprot);
        struct.setErrorIsSet(true);
      }
      if (incoming.get(1)) {
        struct.createdUserId = iprot.readString();
        struct.setCreatedUserIdIsSet(true);
      }
    }
  }

}

