/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef VicKit_CONSTANTS_H
#define VicKit_CONSTANTS_H

#include "VicKit_types.h"

namespace VicKit {

class VicKitConstants {
 public:
  VicKitConstants();

};

extern const VicKitConstants g_VicKit_constants;

} // namespace

#endif
