/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thxsoft.vds.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ContextInvitationMessage implements org.apache.thrift.TBase<ContextInvitationMessage, ContextInvitationMessage._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ContextInvitationMessage");

  private static final org.apache.thrift.protocol.TField PLAYERS_TO_INVITE_FIELD_DESC = new org.apache.thrift.protocol.TField("playersToInvite", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ContextInvitationMessageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ContextInvitationMessageTupleSchemeFactory());
  }

  public List<String> playersToInvite; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLAYERS_TO_INVITE((short)1, "playersToInvite");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLAYERS_TO_INVITE
          return PLAYERS_TO_INVITE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLAYERS_TO_INVITE, new org.apache.thrift.meta_data.FieldMetaData("playersToInvite", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , "UID"))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ContextInvitationMessage.class, metaDataMap);
  }

  public ContextInvitationMessage() {
  }

  public ContextInvitationMessage(
    List<String> playersToInvite)
  {
    this();
    this.playersToInvite = playersToInvite;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ContextInvitationMessage(ContextInvitationMessage other) {
    if (other.isSetPlayersToInvite()) {
      List<String> __this__playersToInvite = new ArrayList<String>();
      for (String other_element : other.playersToInvite) {
        __this__playersToInvite.add(other_element);
      }
      this.playersToInvite = __this__playersToInvite;
    }
  }

  public ContextInvitationMessage deepCopy() {
    return new ContextInvitationMessage(this);
  }

  @Override
  public void clear() {
    this.playersToInvite = null;
  }

  public int getPlayersToInviteSize() {
    return (this.playersToInvite == null) ? 0 : this.playersToInvite.size();
  }

  public java.util.Iterator<String> getPlayersToInviteIterator() {
    return (this.playersToInvite == null) ? null : this.playersToInvite.iterator();
  }

  public void addToPlayersToInvite(String elem) {
    if (this.playersToInvite == null) {
      this.playersToInvite = new ArrayList<String>();
    }
    this.playersToInvite.add(elem);
  }

  public List<String> getPlayersToInvite() {
    return this.playersToInvite;
  }

  public ContextInvitationMessage setPlayersToInvite(List<String> playersToInvite) {
    this.playersToInvite = playersToInvite;
    return this;
  }

  public void unsetPlayersToInvite() {
    this.playersToInvite = null;
  }

  /** Returns true if field playersToInvite is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayersToInvite() {
    return this.playersToInvite != null;
  }

  public void setPlayersToInviteIsSet(boolean value) {
    if (!value) {
      this.playersToInvite = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PLAYERS_TO_INVITE:
      if (value == null) {
        unsetPlayersToInvite();
      } else {
        setPlayersToInvite((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PLAYERS_TO_INVITE:
      return getPlayersToInvite();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PLAYERS_TO_INVITE:
      return isSetPlayersToInvite();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ContextInvitationMessage)
      return this.equals((ContextInvitationMessage)that);
    return false;
  }

  public boolean equals(ContextInvitationMessage that) {
    if (that == null)
      return false;

    boolean this_present_playersToInvite = true && this.isSetPlayersToInvite();
    boolean that_present_playersToInvite = true && that.isSetPlayersToInvite();
    if (this_present_playersToInvite || that_present_playersToInvite) {
      if (!(this_present_playersToInvite && that_present_playersToInvite))
        return false;
      if (!this.playersToInvite.equals(that.playersToInvite))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ContextInvitationMessage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ContextInvitationMessage typedOther = (ContextInvitationMessage)other;

    lastComparison = Boolean.valueOf(isSetPlayersToInvite()).compareTo(typedOther.isSetPlayersToInvite());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayersToInvite()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playersToInvite, typedOther.playersToInvite);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ContextInvitationMessage(");
    boolean first = true;

    sb.append("playersToInvite:");
    if (this.playersToInvite == null) {
      sb.append("null");
    } else {
      sb.append(this.playersToInvite);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ContextInvitationMessageStandardSchemeFactory implements SchemeFactory {
    public ContextInvitationMessageStandardScheme getScheme() {
      return new ContextInvitationMessageStandardScheme();
    }
  }

  private static class ContextInvitationMessageStandardScheme extends StandardScheme<ContextInvitationMessage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ContextInvitationMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLAYERS_TO_INVITE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.playersToInvite = new ArrayList<String>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  String _elem10; // required
                  _elem10 = iprot.readString();
                  struct.playersToInvite.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setPlayersToInviteIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ContextInvitationMessage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.playersToInvite != null) {
        oprot.writeFieldBegin(PLAYERS_TO_INVITE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.playersToInvite.size()));
          for (String _iter11 : struct.playersToInvite)
          {
            oprot.writeString(_iter11);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ContextInvitationMessageTupleSchemeFactory implements SchemeFactory {
    public ContextInvitationMessageTupleScheme getScheme() {
      return new ContextInvitationMessageTupleScheme();
    }
  }

  private static class ContextInvitationMessageTupleScheme extends TupleScheme<ContextInvitationMessage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ContextInvitationMessage struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPlayersToInvite()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPlayersToInvite()) {
        {
          oprot.writeI32(struct.playersToInvite.size());
          for (String _iter12 : struct.playersToInvite)
          {
            oprot.writeString(_iter12);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ContextInvitationMessage struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.playersToInvite = new ArrayList<String>(_list13.size);
          for (int _i14 = 0; _i14 < _list13.size; ++_i14)
          {
            String _elem15; // required
            _elem15 = iprot.readString();
            struct.playersToInvite.add(_elem15);
          }
        }
        struct.setPlayersToInviteIsSet(true);
      }
    }
  }

}

