/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thxsoft.vds.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MessageReplyContent implements org.apache.thrift.TBase<MessageReplyContent, MessageReplyContent._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MessageReplyContent");

  private static final org.apache.thrift.protocol.TField AUTHOR_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("authorUserId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField REPLY_FIELD_DESC = new org.apache.thrift.protocol.TField("reply", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MessageReplyContentStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MessageReplyContentTupleSchemeFactory());
  }

  public long authorUserId; // required
  public ByteBuffer reply; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    AUTHOR_USER_ID((short)1, "authorUserId"),
    REPLY((short)2, "reply");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // AUTHOR_USER_ID
          return AUTHOR_USER_ID;
        case 2: // REPLY
          return REPLY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __AUTHORUSERID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.AUTHOR_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("authorUserId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.REPLY, new org.apache.thrift.meta_data.FieldMetaData("reply", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MessageReplyContent.class, metaDataMap);
  }

  public MessageReplyContent() {
  }

  public MessageReplyContent(
    long authorUserId,
    ByteBuffer reply)
  {
    this();
    this.authorUserId = authorUserId;
    setAuthorUserIdIsSet(true);
    this.reply = reply;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MessageReplyContent(MessageReplyContent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.authorUserId = other.authorUserId;
    if (other.isSetReply()) {
      this.reply = org.apache.thrift.TBaseHelper.copyBinary(other.reply);
;
    }
  }

  public MessageReplyContent deepCopy() {
    return new MessageReplyContent(this);
  }

  @Override
  public void clear() {
    setAuthorUserIdIsSet(false);
    this.authorUserId = 0;
    this.reply = null;
  }

  public long getAuthorUserId() {
    return this.authorUserId;
  }

  public MessageReplyContent setAuthorUserId(long authorUserId) {
    this.authorUserId = authorUserId;
    setAuthorUserIdIsSet(true);
    return this;
  }

  public void unsetAuthorUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __AUTHORUSERID_ISSET_ID);
  }

  /** Returns true if field authorUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetAuthorUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __AUTHORUSERID_ISSET_ID);
  }

  public void setAuthorUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __AUTHORUSERID_ISSET_ID, value);
  }

  public byte[] getReply() {
    setReply(org.apache.thrift.TBaseHelper.rightSize(reply));
    return reply == null ? null : reply.array();
  }

  public ByteBuffer bufferForReply() {
    return reply;
  }

  public MessageReplyContent setReply(byte[] reply) {
    setReply(reply == null ? (ByteBuffer)null : ByteBuffer.wrap(reply));
    return this;
  }

  public MessageReplyContent setReply(ByteBuffer reply) {
    this.reply = reply;
    return this;
  }

  public void unsetReply() {
    this.reply = null;
  }

  /** Returns true if field reply is set (has been assigned a value) and false otherwise */
  public boolean isSetReply() {
    return this.reply != null;
  }

  public void setReplyIsSet(boolean value) {
    if (!value) {
      this.reply = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case AUTHOR_USER_ID:
      if (value == null) {
        unsetAuthorUserId();
      } else {
        setAuthorUserId((Long)value);
      }
      break;

    case REPLY:
      if (value == null) {
        unsetReply();
      } else {
        setReply((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case AUTHOR_USER_ID:
      return Long.valueOf(getAuthorUserId());

    case REPLY:
      return getReply();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case AUTHOR_USER_ID:
      return isSetAuthorUserId();
    case REPLY:
      return isSetReply();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MessageReplyContent)
      return this.equals((MessageReplyContent)that);
    return false;
  }

  public boolean equals(MessageReplyContent that) {
    if (that == null)
      return false;

    boolean this_present_authorUserId = true;
    boolean that_present_authorUserId = true;
    if (this_present_authorUserId || that_present_authorUserId) {
      if (!(this_present_authorUserId && that_present_authorUserId))
        return false;
      if (this.authorUserId != that.authorUserId)
        return false;
    }

    boolean this_present_reply = true && this.isSetReply();
    boolean that_present_reply = true && that.isSetReply();
    if (this_present_reply || that_present_reply) {
      if (!(this_present_reply && that_present_reply))
        return false;
      if (!this.reply.equals(that.reply))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(MessageReplyContent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MessageReplyContent typedOther = (MessageReplyContent)other;

    lastComparison = Boolean.valueOf(isSetAuthorUserId()).compareTo(typedOther.isSetAuthorUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuthorUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authorUserId, typedOther.authorUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReply()).compareTo(typedOther.isSetReply());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReply()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reply, typedOther.reply);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MessageReplyContent(");
    boolean first = true;

    sb.append("authorUserId:");
    sb.append(this.authorUserId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("reply:");
    if (this.reply == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.reply, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MessageReplyContentStandardSchemeFactory implements SchemeFactory {
    public MessageReplyContentStandardScheme getScheme() {
      return new MessageReplyContentStandardScheme();
    }
  }

  private static class MessageReplyContentStandardScheme extends StandardScheme<MessageReplyContent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MessageReplyContent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // AUTHOR_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.authorUserId = iprot.readI64();
              struct.setAuthorUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REPLY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.reply = iprot.readBinary();
              struct.setReplyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MessageReplyContent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(AUTHOR_USER_ID_FIELD_DESC);
      oprot.writeI64(struct.authorUserId);
      oprot.writeFieldEnd();
      if (struct.reply != null) {
        oprot.writeFieldBegin(REPLY_FIELD_DESC);
        oprot.writeBinary(struct.reply);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MessageReplyContentTupleSchemeFactory implements SchemeFactory {
    public MessageReplyContentTupleScheme getScheme() {
      return new MessageReplyContentTupleScheme();
    }
  }

  private static class MessageReplyContentTupleScheme extends TupleScheme<MessageReplyContent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MessageReplyContent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAuthorUserId()) {
        optionals.set(0);
      }
      if (struct.isSetReply()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetAuthorUserId()) {
        oprot.writeI64(struct.authorUserId);
      }
      if (struct.isSetReply()) {
        oprot.writeBinary(struct.reply);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MessageReplyContent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.authorUserId = iprot.readI64();
        struct.setAuthorUserIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.reply = iprot.readBinary();
        struct.setReplyIsSet(true);
      }
    }
  }

}

