/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thxsoft.vds.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ResLoadFollowerUIDs implements org.apache.thrift.TBase<ResLoadFollowerUIDs, ResLoadFollowerUIDs._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ResLoadFollowerUIDs");

  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField FOLLOWER_UIDS_FIELD_DESC = new org.apache.thrift.protocol.TField("followerUIDs", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ResLoadFollowerUIDsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ResLoadFollowerUIDsTupleSchemeFactory());
  }

  public ErrorDesc error; // required
  public List<String> followerUIDs; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ERROR((short)1, "error"),
    FOLLOWER_UIDS((short)2, "followerUIDs");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ERROR
          return ERROR;
        case 2: // FOLLOWER_UIDS
          return FOLLOWER_UIDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ErrorDesc.class)));
    tmpMap.put(_Fields.FOLLOWER_UIDS, new org.apache.thrift.meta_data.FieldMetaData("followerUIDs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , "UID"))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ResLoadFollowerUIDs.class, metaDataMap);
  }

  public ResLoadFollowerUIDs() {
  }

  public ResLoadFollowerUIDs(
    ErrorDesc error,
    List<String> followerUIDs)
  {
    this();
    this.error = error;
    this.followerUIDs = followerUIDs;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ResLoadFollowerUIDs(ResLoadFollowerUIDs other) {
    if (other.isSetError()) {
      this.error = new ErrorDesc(other.error);
    }
    if (other.isSetFollowerUIDs()) {
      List<String> __this__followerUIDs = new ArrayList<String>();
      for (String other_element : other.followerUIDs) {
        __this__followerUIDs.add(other_element);
      }
      this.followerUIDs = __this__followerUIDs;
    }
  }

  public ResLoadFollowerUIDs deepCopy() {
    return new ResLoadFollowerUIDs(this);
  }

  @Override
  public void clear() {
    this.error = null;
    this.followerUIDs = null;
  }

  public ErrorDesc getError() {
    return this.error;
  }

  public ResLoadFollowerUIDs setError(ErrorDesc error) {
    this.error = error;
    return this;
  }

  public void unsetError() {
    this.error = null;
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return this.error != null;
  }

  public void setErrorIsSet(boolean value) {
    if (!value) {
      this.error = null;
    }
  }

  public int getFollowerUIDsSize() {
    return (this.followerUIDs == null) ? 0 : this.followerUIDs.size();
  }

  public java.util.Iterator<String> getFollowerUIDsIterator() {
    return (this.followerUIDs == null) ? null : this.followerUIDs.iterator();
  }

  public void addToFollowerUIDs(String elem) {
    if (this.followerUIDs == null) {
      this.followerUIDs = new ArrayList<String>();
    }
    this.followerUIDs.add(elem);
  }

  public List<String> getFollowerUIDs() {
    return this.followerUIDs;
  }

  public ResLoadFollowerUIDs setFollowerUIDs(List<String> followerUIDs) {
    this.followerUIDs = followerUIDs;
    return this;
  }

  public void unsetFollowerUIDs() {
    this.followerUIDs = null;
  }

  /** Returns true if field followerUIDs is set (has been assigned a value) and false otherwise */
  public boolean isSetFollowerUIDs() {
    return this.followerUIDs != null;
  }

  public void setFollowerUIDsIsSet(boolean value) {
    if (!value) {
      this.followerUIDs = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((ErrorDesc)value);
      }
      break;

    case FOLLOWER_UIDS:
      if (value == null) {
        unsetFollowerUIDs();
      } else {
        setFollowerUIDs((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ERROR:
      return getError();

    case FOLLOWER_UIDS:
      return getFollowerUIDs();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ERROR:
      return isSetError();
    case FOLLOWER_UIDS:
      return isSetFollowerUIDs();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ResLoadFollowerUIDs)
      return this.equals((ResLoadFollowerUIDs)that);
    return false;
  }

  public boolean equals(ResLoadFollowerUIDs that) {
    if (that == null)
      return false;

    boolean this_present_error = true && this.isSetError();
    boolean that_present_error = true && that.isSetError();
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (!this.error.equals(that.error))
        return false;
    }

    boolean this_present_followerUIDs = true && this.isSetFollowerUIDs();
    boolean that_present_followerUIDs = true && that.isSetFollowerUIDs();
    if (this_present_followerUIDs || that_present_followerUIDs) {
      if (!(this_present_followerUIDs && that_present_followerUIDs))
        return false;
      if (!this.followerUIDs.equals(that.followerUIDs))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ResLoadFollowerUIDs other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ResLoadFollowerUIDs typedOther = (ResLoadFollowerUIDs)other;

    lastComparison = Boolean.valueOf(isSetError()).compareTo(typedOther.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, typedOther.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFollowerUIDs()).compareTo(typedOther.isSetFollowerUIDs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFollowerUIDs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.followerUIDs, typedOther.followerUIDs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ResLoadFollowerUIDs(");
    boolean first = true;

    sb.append("error:");
    if (this.error == null) {
      sb.append("null");
    } else {
      sb.append(this.error);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("followerUIDs:");
    if (this.followerUIDs == null) {
      sb.append("null");
    } else {
      sb.append(this.followerUIDs);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (error != null) {
      error.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResLoadFollowerUIDsStandardSchemeFactory implements SchemeFactory {
    public ResLoadFollowerUIDsStandardScheme getScheme() {
      return new ResLoadFollowerUIDsStandardScheme();
    }
  }

  private static class ResLoadFollowerUIDsStandardScheme extends StandardScheme<ResLoadFollowerUIDs> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ResLoadFollowerUIDs struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.error = new ErrorDesc();
              struct.error.read(iprot);
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FOLLOWER_UIDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list64 = iprot.readListBegin();
                struct.followerUIDs = new ArrayList<String>(_list64.size);
                for (int _i65 = 0; _i65 < _list64.size; ++_i65)
                {
                  String _elem66; // required
                  _elem66 = iprot.readString();
                  struct.followerUIDs.add(_elem66);
                }
                iprot.readListEnd();
              }
              struct.setFollowerUIDsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ResLoadFollowerUIDs struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.error != null) {
        oprot.writeFieldBegin(ERROR_FIELD_DESC);
        struct.error.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.followerUIDs != null) {
        oprot.writeFieldBegin(FOLLOWER_UIDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.followerUIDs.size()));
          for (String _iter67 : struct.followerUIDs)
          {
            oprot.writeString(_iter67);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResLoadFollowerUIDsTupleSchemeFactory implements SchemeFactory {
    public ResLoadFollowerUIDsTupleScheme getScheme() {
      return new ResLoadFollowerUIDsTupleScheme();
    }
  }

  private static class ResLoadFollowerUIDsTupleScheme extends TupleScheme<ResLoadFollowerUIDs> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ResLoadFollowerUIDs struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetError()) {
        optionals.set(0);
      }
      if (struct.isSetFollowerUIDs()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetError()) {
        struct.error.write(oprot);
      }
      if (struct.isSetFollowerUIDs()) {
        {
          oprot.writeI32(struct.followerUIDs.size());
          for (String _iter68 : struct.followerUIDs)
          {
            oprot.writeString(_iter68);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ResLoadFollowerUIDs struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.error = new ErrorDesc();
        struct.error.read(iprot);
        struct.setErrorIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list69 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.followerUIDs = new ArrayList<String>(_list69.size);
          for (int _i70 = 0; _i70 < _list69.size; ++_i70)
          {
            String _elem71; // required
            _elem71 = iprot.readString();
            struct.followerUIDs.add(_elem71);
          }
        }
        struct.setFollowerUIDsIsSet(true);
      }
    }
  }

}

